#!/usr/bin/env bash
# record-demo.sh
#
# Assembles a polished demo video of Arbor.HttpClient from headless-rendered
# screenshots.  No display server is required.
#
# The script:
#   1. Regenerates the source screenshots via the headless E2E test suite.
#   2. Uses ffmpeg to build animated video segments with text overlays:
#        - Intro        app as opened, before any request
#        - Typing       URL "typed" character-by-character (drawtext animation)
#        - Send click   cursor moves to Send button and clicks
#        - Response     HTTP 200 response displayed
#        - Variables    {{variable}} environment feature
#        - Scheduled    background scheduled-job feature
#   3. Concatenates the segments into docs/demo.mp4.
#
# Requirements:
#   ffmpeg 6+        (sudo apt-get install ffmpeg)
#   python3          (for the typing-animation helper)
#   .NET 10 SDK      (for dotnet test)
#
# Usage:
#   ./scripts/record-demo.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SHOTS="${REPO_ROOT}/docs/screenshots"
DOCS="${REPO_ROOT}/docs"
TMP="/tmp/arbor-demo-segments"
FINAL="${DOCS}/demo.mp4"
FPS=30

mkdir -p "${TMP}" "${SHOTS}" "${DOCS}"

# Locate fonts ----------------------------------------------------------------
FONT_B=""
FONT=""
for f in \
    /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf \
    /usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf; do
    [ -f "${f}" ] && FONT_B="${f}" && break
done
for f in \
    /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf \
    /usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf; do
    [ -f "${f}" ] && FONT="${f}" && break
done
: "${FONT_B:=${FONT}}"
echo "Fonts: ${FONT_B} (bold)  ${FONT} (regular)"

# 1. Generate screenshots ------------------------------------------------------
echo "[1/3] Generating screenshots via headless renderer..."
SCREENSHOT_OUTPUT_DIR="${SHOTS}" dotnet test \
    "${REPO_ROOT}/src/Arbor.HttpClient.Desktop.E2E.Tests" \
    --filter "Category=Screenshots" \
    -v minimal 2>&1 | tee "${TMP}/dotnet-test.log" | grep -E "Passed|Failed|Error" || true

for img in state-initial state-response variables scheduled-jobs; do
    [ -f "${SHOTS}/${img}.png" ] || { echo "ERROR: Missing ${SHOTS}/${img}.png"; exit 1; }
done

# 2. Build video segments ------------------------------------------------------
echo "[2/3] Building video segments..."

# Helper: build and write one segment
# make_seg <name> <image> <duration_s> <vf_filter>
make_seg() {
    local name="${1}" img="${2}" dur="${3}" vf="${4}"
    ffmpeg -loop 1 -i "${img}" \
        -t "${dur}" -r "${FPS}" -pix_fmt yuv420p \
        -c:v libx264 -preset ultrafast \
        -vf "${vf}" \
        "${TMP}/${name}.mp4" -y 2>"${TMP}/${name}.log"
    printf "  done: %s (%s s)\n" "${name}" "${dur}"
}

# Caption at top of frame
cap() {
    local text="${1}"
    printf "drawtext=fontfile=%s:text='%s':x=(w-text_w)/2:y=18:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.70:boxborderw=9" \
        "${FONT_B}" "${text}"
}

# Smaller sub-caption below main caption
sub() {
    local text="${1}"
    printf "drawtext=fontfile=%s:text='%s':x=(w-text_w)/2:y=52:fontsize=17:fontcolor=#DDDDDD:box=1:boxcolor=black@0.55:boxborderw=6" \
        "${FONT}" "${text}"
}

# Mouse-cursor highlight (yellow dot) at a given coordinate
cursor() {
    local cx="${1}" cy="${2}"
    printf "drawbox=x=%d:y=%d:w=16:h=16:color=#FFDD44@0.85:t=fill" \
        $(( cx - 8 )) $(( cy - 8 ))
}

# Typing-animation filter -- generated by the Python helper
# Layout: URL text field top-left at approx (591, 69) in the 1300x820 window
DEMO_URL="https://postman-echo.com/get?hello=world"
TYPING_VF="$(python3 "${REPO_ROOT}/scripts/gen_typing_filter.py" \
    "${DEMO_URL}" 591 69 "${FONT}" 8)"

# Segment 1: App just opened (3 s)
make_seg "s1_intro" "${SHOTS}/state-initial.png" 3 \
    "$(cap "Arbor.HttpClient -- cross-platform desktop HTTP client")"

# Segment 2: URL typed character-by-character (6 s)
make_seg "s2_typing" "${SHOTS}/state-initial.png" 6 \
    "${TYPING_VF},$(cap "Type any URL into the request bar...")"

# Segment 3: Cursor moves to Send button and clicks (2 s)
# Send button centre is at approximately (1224, 82)
make_seg "s3_click" "${SHOTS}/state-initial.png" 2 \
    "$(cursor 1224 82),$(cap "Click Send to fire the request")"

# Segment 4: HTTP 200 OK response displayed (6 s)
make_seg "s4_response" "${SHOTS}/state-response.png" 6 \
    "$(cap "200 OK -- response body shown immediately"),$(sub "Status code and JSON body appear as soon as the response arrives")"

# Segment 5: Variables feature (6 s)
make_seg "s5_vars" "${SHOTS}/variables.png" 6 \
    "$(cap "Use {{variables}} for reusable values"),$(sub "Variables are resolved from the active environment before each request")"

# Segment 6: Scheduled jobs (4 s)
make_seg "s6_sched" "${SHOTS}/scheduled-jobs.png" 4 \
    "$(cap "Schedule requests to run automatically"),$(sub "Set an interval and Auto-start for background polling or health-checks")"

# 3. Concatenate segments ------------------------------------------------------
echo "[3/3] Concatenating segments..."

LIST="${TMP}/concat.txt"
: > "${LIST}"
for seg in s1_intro s2_typing s3_click s4_response s5_vars s6_sched; do
    printf "file '%s/%s.mp4'\n" "${TMP}" "${seg}" >> "${LIST}"
done

ffmpeg \
    -f concat -safe 0 -i "${LIST}" \
    -c:v libx264 \
    -crf 24 \
    -preset medium \
    -pix_fmt yuv420p \
    -movflags +faststart \
    -an \
    "${FINAL}" -y 2>"${TMP}/final.log"

SIZE="$(du -sh "${FINAL}" | cut -f1)"
DUR="$(ffprobe -v quiet -show_entries format=duration -of csv=p=0 "${FINAL}" 2>/dev/null || echo "?")"
printf "\nDemo video saved: %s  (%s, %s s)\n" "${FINAL}" "${SIZE}" "${DUR%.*}"
